name: Pyanalyze

on: [push, pull_request]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install
        run: |
          python -m pip install -e .
          python -m pip install pyanalyze==0.10.1
      - name: Run
        run:
          PYTHONPATH=. python -m pyanalyze --config-file pyproject.toml gql_defrag/
          tests/
